FROM jenkins/jenkins:latest

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
COPY jenkins.yaml /config/jenkins.yaml

RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt

ENV CASC_JENKINS_CONFIG /config/jenkins-config.yaml
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
