@Library("shared-library") _

pipeline{
    agent any
    environment {
        MY_TOKEN = credentials('my-token')
    }
    options {
        buildDiscarder(
            logRotator(
                daysToKeepStr: '60'
            )
        )
        disableConcurrentBuilds()
        timeout(
            time: 1,
            unit: 'HOURS'
        )
    }

    stages {

        stage("Loading Shared Library") {
            steps {
                helloWorld('dude')
                howdy(name: 'partner', dayOfWeek: 'Tuesday')
                checkPlease()
            }
        }

        stage("Check location") {
            steps {
                sh 'pwd'
            }
        }

        stage("Check Items") {
            steps {
                sh 'ls -ahl'
            }
        }

        stage("Building new version") {
            steps {
                echo "Building version: ${params.VERSION}"
                echo "log level:  ${params.LOGGING_LEVEL}"
            }
        }
    }
}